name: Build and Release

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Triggers the workflow on a push event, but only for version tags (e.g., v1.0, v2.3.4).
  push:
    tags:
      - 'v*'

env:
  # =================================================================
  # == CONFIGURATION FOR YOUR SELF-HOSTED RUNNER
  # =================================================================
  # Adjust these paths to match your self-hosted runner's environment.
  #
  # Path to your Qt 6 installation directory.
  QT_DIR: C:\Qt\6.9.1\msvc2022_64
  #
  # Path to the Visual Studio Developer Command Prompt initialization script.
  # This is the standard way to set up the MSVC compiler environment.
  VCVARS_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  #
  # (Optional) Path to the UPX executable. Download from https://upx.github.io/
  UPX_PATH: "C:\\upx\\upx.exe"

jobs:
  build-and-release:
    # This job runs on a self-hosted runner, as requested.
    # Ensure your runner has a label 'self-hosted'.
    runs-on: self-hosted
    permissions:
      # This permission is required for the softprops/action-gh-release action
      # to create a GitHub Release and upload assets.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Version Number
        id: get_version
        # Use the tag name for the version. If not a tag, generate a dev version string.
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $date = Get-Date -Format "yyyy.MM.dd"
            $version = "dev-$date-${{ github.run_number }}"
          }
          "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: powershell

      - name: Configure CMake
        run: |
          call "%VCVARS_PATH%"
          cmake -S . -B build -DCMAKE_PREFIX_PATH="%QT_DIR%"
        shell: cmd

      - name: Build with CMake
        run: |
          call "%VCVARS_PATH%"
          cmake --build build --config Release
        shell: cmd

      - name: Optimize and Compress Release Files
        if: env.UPX_PATH != ''
        run: |
          echo "--- Reducing package size by removing unnecessary files ---"
          del /q /s build\Release\*.pdb > nul 2>&1
          if exist build\Release\translations rmdir /s /q build\Release\translations
          if exist build\Release\opengl32sw.dll del /q build\Release\opengl32sw.dll
          if exist build\Release\Qt6Qml*.dll del /q build\Release\Qt6Qml*.dll
          if exist build\Release\Qt6Quick*.dll del /q build\Release\Qt6Quick*.dll
          if exist build\Release\Qt6WebEngine*.dll del /q build\Release\Qt6WebEngine*.dll
          if exist build\Release\QtWebEngineProcess.exe del /q build\Release\QtWebEngineProcess.exe

          echo "--- Compressing executables with UPX ---"
          echo "Compressing main executable..."
          "%UPX_PATH%" --best --lzma build/Release/winsys-overlay.exe
          echo "Compressing DLLs (forcing due to GUARD_CF)..."
          "%UPX_PATH%" --best --lzma --force build/Release/*.dll
        shell: cmd

      - name: Package Release Files
        id: package
        run: |
          $archiveName = "winsys-overlay-${{ steps.get_version.outputs.VERSION }}.zip"
          Compress-Archive -Path build/Release/* -DestinationPath $archiveName -Force
          "ARCHIVE_NAME=$archiveName" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: powershell

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: winsys-overlay-build
          path: ${{ steps.package.outputs.ARCHIVE_NAME }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.ARCHIVE_NAME }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}."